# -*- coding: utf-8 -*-
"""matrix_ops.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q4b13quZVNiDBbk8U2jQJsJTBzRweOGp
"""

# Matrix Addition
def matrix_add(A, B):

    if len(A) != len(B) or len(A[0]) != len(B[0]):
        print("Matrix dimensions do not match for addition")
        return None

    result = []

    for i in range(len(A)):
        row = []
        for j in range(len(A[0])):
            row.append(A[i][j] + B[i][j])
        result.append(row)

    return result


# Matrix Transpose
def matrix_transpose(matrix):

    # using nested list comprehension
    transpose = [[row[i] for row in matrix] for i in range(len(matrix[0]))]

    return transpose


# Matrix Multiplication
def matrix_multiply(A, B):

    # check dimension compatibility
    if len(A[0]) != len(B):
        print("Matrix dimensions do not match for multiplication")
        return None

    result = []

    for row_a in A:
        new_row = []

        for col_b in zip(*B):
            value = sum(a * b for a, b in zip(row_a, col_b))
            new_row.append(value)

        result.append(new_row)

    return result


# -----------------------
# Testing the functions
# -----------------------

a = [[1, 2],
     [3, 4]]

b = [[5, 6],
     [7, 8]]

print("Matrix Addition:")
print(matrix_add(a, b))

print("Matrix Transpose:")
print(matrix_transpose(a))

print("Matrix Multiplication:")
print(matrix_multiply(a, b))


# Another test with different size matrices
c = [[1, 2, 3],
     [4, 5, 6]]

d = [[7, 8],
     [9, 10],
     [11, 12]]

print("Multiplication with different size matrices:")
print(matrix_multiply(c, d))

