# -*- coding: utf-8 -*-
"""student_system

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aCLTYExf1RZSA4fAdpN-zNIiY5cLMEdF
"""

# student_system.py

# Initial student data
records = [
    ["Aman", "Math", 88],
    ["Priya", "Physics", 91],
    ["Rahul", "Math", 76],
    ["Neha", "Chemistry", 85],
    ["Karan", "Physics", 79],
    ["Sneha", "Math", 92],
    ["Rohit", "Chemistry", 73],
    ["Anjali", "Physics", 87],
    ["Vikas", "Math", 81],
    ["Pooja", "Chemistry", 90]
]


def add_student(name, subject, marks):
    global records

    # check if same student already has marks for same subject
    for r in records:
        if r[0] == name and r[1] == subject:
            print("This record already exists")
            return

    records.append([name, subject, marks])
    print("Student added")


def get_toppers(subject):
    subject_list = []

    for r in records:
        if r[1] == subject:
            subject_list.append(r)

    if len(subject_list) == 0:
        print("No students found for this subject")
        return

    subject_list = sorted(subject_list, key=lambda x: x[2], reverse=True)

    print("Top students in", subject)
    for s in subject_list[:3]:
        print(s)


def class_average(subject):
    marks = [r[2] for r in records if r[1] == subject]

    if len(marks) == 0:
        print("No records for this subject")
        return

    avg = sum(marks) / len(marks)
    print("Average marks in", subject, "=", avg)


def above_average_students():
    if len(records) == 0:
        print("No data available")
        return

    total = sum(r[2] for r in records)
    overall_avg = total / len(records)

    print("Overall class average:", overall_avg)

    students = [r for r in records if r[2] > overall_avg]

    print("Students scoring above average:")
    for s in students:
        print(s)


def remove_student(name):
    global records

    records = [r for r in records if r[0] != name]
    print("Student removed if present")


def save_records():
    file = open("students.txt", "w")

    for r in records:
        line = r[0] + "," + r[1] + "," + str(r[2]) + "\n"
        file.write(line)

    file.close()
    print("Records saved to students.txt")


while True:

    print("\nStudent Management System")
    print("1 Add student")
    print("2 Show toppers")
    print("3 Show class average")
    print("4 Show above-average students")
    print("5 Remove student")
    print("6 Exit")

    choice = input("Enter your choice: ")

    if choice == "1":
        name = input("Enter name: ")
        subject = input("Enter subject: ")
        marks = int(input("Enter marks: "))
        add_student(name, subject, marks)

    elif choice == "2":
        subject = input("Enter subject: ")
        get_toppers(subject)

    elif choice == "3":
        subject = input("Enter subject: ")
        class_average(subject)

    elif choice == "4":
        above_average_students()

    elif choice == "5":
        name = input("Enter name to remove: ")
        remove_student(name)

    elif choice == "6":
        save_records()
        print("Program ended")
        break

    else:
        print("Invalid option")

